################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 1
# footer content
[en.params]
footer_content = ""
