#################### default parameters ################################
# favicon
favicon = "images/logo-sr.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "300x"
# logo text will only show when logo is missing.
logo_text = "Sander Rozemuller"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "All about automation, Azure, M365, AVD and more."
author = "Sander Rozemuller"
image = "images/author.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = " "
mobile = "+"
email = "sander"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# Holidays
christmas = true
lights = true

# featured post title
featured_post_title = ""
recent_post_title = ""
# mainSections = ["blog"]
# about widget content
about_widget_content = "Hi, I'm Sander Rozemuller. I work at Exite ICT (Enschede) as a Cloud Architect. I love to share my knowledge about automation in Azure and M365. </br>You can find me on the links below."
# footer content
footer_content = "Copyright © 2022 by Sander Rozemuller. All rights reserved. No part of the information on this web site may be reproduced or posted in any form or by any means without the prior written permission of the publisher. All post are written based on my own experience with no warranties, confers no rights and is not supported by the authors. "
# copyright
copyright = "Copyright [Rozemuller](https://www.rozemuller.com/)"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Welcome **!**"
title_small = "to Sander Rozemuller"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "Are Developer and recently started your own business Already made website to ensure presence wants to develop."
button_label = "Know About Me"
button_link = "about/"

# Advertise
[[featured]]
image = "images/avd-cocktail-menu.png"
link = "/categories/avd-cocktail/"
category = "AVD Automation Cocktail"

[[featured]]
image = "images/security.jpg"
link = "/categories/security/"
category = "Security"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["az-avd","about","mvp","adsense-square","side-menu","adsense-square","categories","adsense-square"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "" # replace this code with yours


############################# social site ########################

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://www.twitter.com/sanderozemuller"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.github.com/srozemuller"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/in/sanderrozemuller/"